package LRMv2;

/* CVS $Id: $ */

import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.ontology.OntProperty;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from LRM-ReAL-schema.ttl
 * 
 * @author Auto-generated by schemagen on 24 Jun 2015 10:54
 */
public class LRM_ReAL_schema {
	/**
	 * <p>
	 * The ontology model that holds the vocabulary terms
	 * </p>
	 */
	private static OntModel m_model = ModelFactory.createOntologyModel(
			OntModelSpec.RDFS_MEM, null);

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://xrce.xerox.com/LRM#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final OntProperty describedBy = m_model
			.createOntProperty("http://xrce.xerox.com/LRM#describedBy");

	public static final OntProperty specifiedBy = m_model
			.createOntProperty("http://xrce.xerox.com/LRM#specifiedBy");

	public static final OntClass Description = m_model
			.createClass("http://xrce.xerox.com/LRM#Description");

	public static final OntClass Specification = m_model
			.createClass("http://xrce.xerox.com/LRM#Specification");

}
